use crate::lexer::tokens::{Token, LexingError};
use crate::parser::ast;

grammar;

extern {
  type Location = usize;
  type Error = LexingError;

  enum Token {
    "def"      => Token::Def,
    "extern"   => Token::Extern,
    "if"       => Token::If,
    "then"     => Token::Then,
    "else"     => Token::Else,
    "for"      => Token::For,
    "in"       => Token::In,
    "id"       => Token::Identifier(<String>),
    "lit_d"    => Token::Number(<f64>),
    "("        => Token::LParen,
    ")"        => Token::RParen,
    "+"        => Token::Add,
    "-"        => Token::Sub,
    "/"        => Token::Div,
    "*"        => Token::Mult,
    ">="       => Token::GreaterEq,
    "<="       => Token::LessEq,
    ">"        => Token::Greater,
    "<"        => Token::Less,
    "="        => Token::Equal,
    "/="       => Token::NotEqual,
    ","        => Token::Comma,
    ";"        => Token::Semicolon,
  }
}

pub Program: Vec<ast::Decl> = {
  <stmts:Decl*>   => stmts,
  <expr:Expr> => vec![ast::Decl::Function { proto: ast::Prototype {name: "__anon_expr".to_string(), args: Vec::new() }, body: expr}],
}

pub Decl: ast::Decl = {
  "extern" <name:"id"> "(" <args:ParamList> ")"      => ast::Decl::Extern(ast::Prototype {name, args}),
  "def" <name:"id"> "(" <args:ParamList> ")" <body:Expr> => ast::Decl::Function { proto: ast::Prototype { name, args }, body}

}

pub Expr: Box<ast::Expr> = {
  ControlExpr,
}

pub ControlExpr: Box<ast::Expr> = {
   "if" <cond:Expr> "then" <fst:Expr> "else" <snd:Expr> => Box::new(ast::Expr::IfThenElse {cond, fst, snd}),
   "for" <var_name:"id"> "=" <start:Expr> "," <end:Expr> "," <step:Expr> "in" <body:Expr> => Box::new(ast::Expr::ForLoop {var_name, start, end, step, body}),   
   RelExpr,
};

pub RelExpr: Box<ast::Expr> = {
    <left:Tier1> "<" <right:Tier1>  => Box::new(ast::Expr::Binary {op: ast::BinaryOp::Lt, left , right }), 
    Tier1,
}

pub Tier1: Box<ast::Expr> = {
  Tier<Tier1_Op,Tier2>,
}

pub Tier2: Box<ast::Expr> = {
  Tier<Tier2_Op,Term>,
}

pub Term: Box<ast::Expr> = {
  <value:"lit_d">                    => Box::new(ast::Expr::DoubleLit {value}),
  <name:"id"> "(" <args:ArgList> ")" => Box::new(ast::Expr::Call {name, args}),
  <name:"id">                        => Box::new(ast::Expr::Var {name}),
  "(" <Expr> ")",
}

pub Param: ast::Arg = {
  <name:"id"> => ast::Arg { name, typ: ast::Type::Double }
}

ParamList: Vec<ast::Arg> = Comma<Param>;
ArgList: Vec<Box<ast::Expr>> = Comma<Expr>;

Tier<Op, Next>: Box<ast::Expr> = {
    <left:Tier<Op, Next>> <op:Op> <right:Next>
        => Box::new(ast::Expr::Binary {
            op,
            left,
            right,
        }),
    Next,
}

Tier1_Op: ast::BinaryOp = {
  "+" => ast::BinaryOp::Add,
  "-" => ast::BinaryOp::Sub,
}

Tier2_Op: ast::BinaryOp = {
  "*" => ast::BinaryOp::Mult,
}


Comma<T>: Vec<T> = {
    <mut v:(<T> ",")*> <e:T?> => match e {
        None => v,
        Some(e) => {
            v.push(e);
            v
        }
    }
};
